extends Node

signal device_changed(new_device: DeviceType)

enum DeviceType {
	KEYBOARD_MOUSE,
	XBOX_CONTROLLER,
	PLAYSTATION_CONTROLLER,
	TOUCH
}

var current_device: DeviceType = DeviceType.KEYBOARD_MOUSE

#func _input(event: InputEvent) -> void:
	#var new_device = current_device
	#
	## 1. Detect Touch
	#if event is InputEventScreenTouch or event is InputEventScreenDrag:
		#new_device = DeviceType.TOUCH
		#
	## 2. Detect Keyboard & Mouse
	#elif event is InputEventKey or event is InputEventMouseButton or event is InputEventMouseMotion:
		## Optional: Filter out tiny mouse twitches if they conflict with controllers
		#if event is InputEventMouseMotion and event.velocity.length() < 10.0:
			#return
		#new_device = DeviceType.KEYBOARD_MOUSE
		#
	## 3. Detect Controllers
	#elif event is InputEventJoypadButton or event is InputEventJoypadMotion:
		## Filter out minor stick drift
		#if event is InputEventJoypadMotion and abs(event.axis_value) < 0.3:
			#return
			#
		## Figure out if it's an Xbox, PlayStation, or Nintendo controller
		#var joy_name = Input.get_joy_name(event.device).to_lower()
		#if "sony" in joy_name or "playstation" in joy_name or "ps" in joy_name:
			#new_device = DeviceType.PLAYSTATION_CONTROLLER
		#else:
			## Default to Xbox layout for general XInput/generic pads
			#new_device = DeviceType.XBOX_CONTROLLER
#
	## If the device actually changed, update and notify the UI
	#if new_device != current_device:
		#current_device = new_device
		#device_changed.emit(current_device)

func _input(event: InputEvent) -> void:
	var new_device = current_device
	
	# Check touch FIRST, or check if it's a mouse event generated BY a touch
	if event is InputEventScreenTouch or event is InputEventScreenDrag or ("is_emulated" in event and event.is_emulated):
		new_device = DeviceType.TOUCH
		
	elif event is InputEventKey or event is InputEventMouseButton or event is InputEventMouseMotion:
		# If 'Emulate Mouse From Touch' is on, a touch event will pass this check.
		# We must explicitly ensure it didn't come from a touch screen.
		if event is InputEventMouseButton and event.is_pressed():
			# In Godot 4, you can check if a mouse event was emulated from touch
			# If it is emulated, skip setting it to KEYBOARD_MOUSE
			if Engine.has_singleton("DisplayServer") and DisplayServer.tts_is_speaking(): 
				pass # placeholder for edge case logic
				
		if event is InputEventMouseMotion and event.velocity.length() < 10.0:
			return
			
		# Double check it's not a touch disguised as a mouse click
		if new_device != DeviceType.TOUCH:
			new_device = DeviceType.KEYBOARD_MOUSE
			
	# 3. Detect Controllers
	elif event is InputEventJoypadButton or event is InputEventJoypadMotion:
		# Filter out minor stick drift
		if event is InputEventJoypadMotion and abs(event.axis_value) < 0.3:
			return
			
		# Figure out if it's an Xbox, PlayStation, or Nintendo controller
		var joy_name = Input.get_joy_name(event.device).to_lower()
		if "sony" in joy_name or "playstation" in joy_name or "ps" in joy_name:
			new_device = DeviceType.PLAYSTATION_CONTROLLER
		else:
			# Default to Xbox layout for general XInput/generic pads
			new_device = DeviceType.XBOX_CONTROLLER

	# If the device actually changed, update and notify the UI
	if new_device != current_device:
		current_device = new_device
		device_changed.emit(current_device)
